# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07c01e97c37e4be2e7374334aab82481b2f21ad40713219fecc7705d680f2c17169df86fb82787e91bdbfb167dc168d8debc2a2be3ec92c791681f8a91387486

test:
  secret_key_base: 64e714e693810cbc6584da1ce5e5e45146a7a670651faf822d105723ca11297e31035b036c5193f190707de83cedf3eae3fe321e48aab56b768ef6b1d7d79798

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
